server:
  port: 8080
  address: localhost
  servlet:
    context-path: /leavescoffee

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/leavescoffee"
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect




